### PR TITLE
fix #51

### LINKED ISSUE #51: OpenGL error 0x0501 in D:\dev\engine-v5\cocos\renderer\backend\opengl\TextureGL.cpp cocos2d::backend::Texture2DGL::updateData 206
- cocos2d-x version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. 
2.

### PR DESCRIPTION
**Pull request by halx99**

### CODE REVIEW

File: cocos/2d/CCLayer.cpp [hunk 1]
```diff
@@ -288,7 +288,7 @@ LayerColor::LayerColor()
     _blendFunc = BlendFunc::ALPHA_PREMULTIPLIED;
     
     auto& pipelineDescriptor = _customCommand.getPipelineDescriptor();
-    auto* program = backend::Program::getBuiltinProgram(backend::ProgramType::POSITION_COLOR);
+    auto* program = backend::Program::getBuiltinProgram(backend::ProgramType::POSITION_COLOR); // TODO: noMVP?
```
Comment (halx99) [inline cocos/2d/CCLayer.cpp]: should remove comment

File: cocos/editor-support/cocostudio/ActionTimeline/CCBoneNode.cpp [hunk 2]
```diff
@@ -414,7 +414,7 @@ bool BoneNode::init()
     updateColor();
 
     auto& pipelineDescriptor = _customCommand.getPipelineDescriptor();
-    auto* program = cocos2d::backend::Program::getBuiltinProgram(cocos2d::backend::ProgramType::POSITION);
+    auto* program = cocos2d::backend::Program::getBuiltinProgram(cocos2d::backend::ProgramType::POSITION_COLOR); // TODO: noMVP?
```
Comment (halx99) [inline cocos/editor-support/cocostudio/ActionTimeline/CCBoneNode.cpp]: after test, remove comment

File: cocos/editor-support/cocostudio/ActionTimeline/CCSkeletonNode.cpp [hunk 3]
```diff
@@ -53,7 +53,7 @@ bool SkeletonNode::init()
 
     // init _customCommand  
     auto& pipelineDescriptor = _customCommand.getPipelineDescriptor();
-    auto* program = cocos2d::backend::Program::getBuiltinProgram(cocos2d::backend::ProgramType::POSITION);
+    auto* program = cocos2d::backend::Program::getBuiltinProgram(cocos2d::backend::ProgramType::POSITION_COLOR); // TODO: noMVP?
```
Comment (halx99) [inline cocos/editor-support/cocostudio/ActionTimeline/CCSkeletonNode.cpp]: after test, remove comment
